---
# Source: common/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-name-received
  labels:
    helm.sh/chart: common-0.7.0
    app.kubernetes.io/name: common
    app.kubernetes.io/instance: common
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    wave.pusher.com/update-on-config-change: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: common
      app.kubernetes.io/instance: common
  template:
    metadata:
      labels:
        app.kubernetes.io/name: common
        app.kubernetes.io/instance: common
    spec:
      imagePullSecrets:
      serviceAccountName: no-name-received
      containers:
      - name: common
        image: nginx:latest
        imagePullPolicy: Always
        
        envFrom:
        
        resources:
            null
        
        
      
        volumeMounts:
        - mountPath: my/shit/t.txt
          name: test-name
          
          subPath: shit/path/t.txt
          
      volumes:
      - name: test-name

        
        
        
        persistentVolumeClaim:
          claimName: test-claim
